---
- hosts: localhost
  become: yes
  roles:
    - { role: base, tags: ['base'] }
    - { role: grsec, tags: ['grsec'] }
    - { role: ssh, tags: ['ssh'] }
    - { role: dotfiles, tags: ['dotfiles'] }
    - { role: ssd, tags: ['ssd'] }
    - { role: fonts, tags: ['fonts'] }
    - { role: x, tags: ['x'] }
    - { role: slim, tags: ['slim'] }
    - { role: i3, tags: ['i3'] }
    - { role: iptables, tags: ['iptables'] }
    - { role: network, tags: ['network'] }
    - { role: networkmanager, tags: ['networkmanager'] }
    - { role: ntp, tags: ['ntp'] }
    - { role: firejail, tags: ['firejail'] }
    - { role: unbound, tags: ['unbound'] }
    - { role: editors, tags: ['editors'] }
    - { role: browsers, tags: ['browsers'] }
    - { role: media, tags: ['media'] }
    - { role: laptop, tags: ['laptop'] }
    - { role: thinkpad, tags: ['thinkpad'], when: "'ThinkPad' in ansible_product_version" }
    - { role: macbook, tags: ['macbook'], when: "'MacBook' in ansible_product_name" }
    - { role: screensaver, tags: ['screensaver'] }
    - { role: chat, tags: ['chat'] }
    - { role: git-annex, tags: ['git-annex'] }
    - { role: ledger, tags: ['ledger'] }
    - { role: mail, tags: ['mail'] }
    - { role: office, tags: ['office'] }
    - { role: redshift, tags: ['redshift'] }
    - { role: rtorrent, tags: ['rtorrent'] }
    - { role: vm, tags: ['vm'] }
    - { role: yubikey, tags: ['yubikey'] }
    - { role: virtualenv, tags: ['virtualenv'] }
    - { role: backup, tags: ['backup'] }
    - { role: tarsnap, tags: ['tarsnap'] }
    - { role: mapping, tags: ['mapping'] }
    - { role: sound, tags: ['sound'] }
    - { role: archive, tags: ['archive'] }
    - { role: filesystems, tags: ['filesystems'] }
    - { role: pim, tags: ['pim'] }
    - { role: radio, tags: ['radio'] }
    - { role: formd, tags: ['formd'] }
  vars_prompt:
    - name: user_password
      prompt: "Enter desired user password"

