---
- hosts: localhost
  sudo: yes
  roles:
    - { role: base }
    - { role: fonts }
    - { role: x }
    - { role: i3 }
    - { role: network }
    - { role: ntp }
    - { role: unbound }
    - { role: vim }
    - { role: browsers }
    - { role: media }
    - { role: laptop }
    - { role: thinkpad }
    - { role: screensaver }
    - { role: firejail }
    - { role: chat }
    - { role: git-annex }
    - { role: ledger }
    - { role: mail }
    - { role: office }
    - { role: redshift }
    - { role: rtorrent }
    - { role: vm }
    - { role: yubikey }
    - { role: development }
    - { role: backup }
    - { role: mapping }
    - { role: sound }
  vars_prompt:
    - name: user_password
      prompt: "Enter desired user password"

