---
- name: Install rcm
  aur: name=rcm user={{ user.name }}
  when: dotfiles is defined
  tags:
    - aur

- name: Clone user dotfiles
  git:
    repo: "{{ dotfiles.url }}"
    version: work
    dest: {{ repository_dir }}/dotfiles
    accept_hostkey=yes
    update=no
  when: dotfiles is defined
  become: yes
  become_user: "{{ user.name }}"

- name: Install user dotfiles
  command: rcup -d ={{ repository_dir }}/dotfiles {{ dotfiles.rcup_flags }}
  when: dotfiles is defined
  become: yes
  become_user: "{{ user.name }}"
