---
- name: Install libOTR
  pacman: name=libotr state=present
  tags:
    - bitlbee

- name: Install Bitlbee
  pacman: name=bitlbee state=present
  tags:
    - bitlbee

- name: Copy Bitlbee configuration file
  copy: src=bitlbee.conf dest=/etc/bitlbee/bitlbee.conf
  tags:
    - bitlbee

- name: Ensure proper ownership of configuration directory
  file: path=/var/lib/bitlbee group=bitlbee owner=bitlbee
  tags:
    - bitlbee

- name: Create Bitlbee systemd unit file directory
  file: path=/etc/systemd/system/bitlbee.service.d state=directory
  tags:
    - bitlbee
    - firejail

- name: Push Bitlbee socket unit file
  copy: src=bitlbee-service-override.conf dest=/etc/systemd/system/bitlbee.service.d/override.conf
  tags:
    - bitlbee
    - firejail

- name: Enable and start Bitlbee
  service: name=bitlbee enabled=yes state=started
  tags:
    - bitlbee
