---
- name: Install Tarsnap
  pacman: name=tarsnap state=present

- name: Install rsnapshot
  pacman: name=rsnapshot state=present

- name: Install attic
  aur: name=attic user={{ user.name }}
  tags:
    - aur
- name: Install atticmatic
  aur: name=atticmatic user={{ user.name }}
  tags:
    - aur
