---
- name: Install Tarsnap
  pacman: name=tarsnap state=present
  tags:
    - tarsnap

- name: Copy default Tarsnap config
  copy: src=/etc/tarsnap/tarsnap.conf.sample dest=/etc/tarsnap/tarsnap.conf
  tags:
    - tarsnap

- name: Create Tarsnap cache dir
  file: path=/usr/local/tarsnap-cache state=directory
  tags:
    - tarsnap

- name: Humanize Tarsnap numbers
  lineinfile: dest=/etc/tarsnap/tarsnap.conf
              state=present
              line=humanize-numbers
  tags:
    - tarsnap

- name: Install Tarsnapper into virtual environment
  pip: name=tarsnapper
       virtualenv=/usr/local/env/tarsnapper
       virtualenv_command=virtualenv-2.7
  tags:
    - tarsnap

- name: Link Tarsnapper to bin
  file: src=/usr/local/env/tarsnapper/bin/tarsnapper
        dest=/usr/local/bin/tarsnapper
        state=link
  tags:
    - tarsnap

- name: Create Tarsnapper config include dir
  file: path=/usr/local/etc/tarsnapper.d/ state=directory
  tags:
    - tarsnap

- name: Push Tarsnapper config
  template: src=tarsnapper.conf.j2 dest=/usr/local/etc/tarsnapper.conf
  tags:
    - tarsnap
