---
- name: Install Grsecurity
  pacman: name=linux-grsec state=present
  notify:
    - rebuild grub

- name: Install PaX
  pacman: name={{ item }} state=present
  with_items:
      - paxd
      - pax-utils
      - paxtest
