---
- name: Push trusted network list
  template: src=trusted_networks.j2 dest=/usr/local/etc/trusted_networks

- name: Install OpenVPN
  pacman: name=openvpn state=present

- name: Install MTR
  pacman: name=mtr state=present

- name: Install net-tools
  pacman: name=net-tools state=present

- name: Install bind-tools
  pacman: name=bind-tools state=present

- name: Install whois
  pacman: name=whois state=present

- name: Install netcat
  pacman: name=gnu-netcat state=present

- name: Install lftp
  pacman: name=lftp state=present

- name: Install NetworkManager
  pacman: name=networkmanager state=present

- name: Install NetworkManager OpenVPN plugin
  pacman: name=networkmanager-openvpn state=present

- name: Install NetworkManager applet
  pacman: name=network-manager-applet state=present

- name: Install Xfce notification daemon
  pacman: name=xfce4-notifyd state=present

- name: Install GNOME Keyring
  pacman: name=gnome-keyring state=present

- name: Enable and start NetworkManager
  service: name=NetworkManager.service enabled=yes state=started

- name: Enable and start NetworkManager dispatcher
  service: name=NetworkManager-dispatcher.service enabled=yes state=started

- include: pdsh.yml
- include: firewall.yml
- include: macchiato.yml
