---
- name: Install fabric
  pacman: name=fabric state=present
  tags:
    - python-dev

- name: Install tig
  pacman: name=tig state=present

- name: Install Ruby
  pacman: name=ruby state=present
  tags:
    - ruby-dev
