---
- name: Download YubiKey Personalizaiton GUI
  command: cower -dq yubikey-personalization-gui-git
           chdir=/home/{{ user.name }}/{{ aur.dir }}
           creates=/home/{{ user.name }}/{{ aur.dir }}/yubikey-personalization-gui-git
  tags:
    - aur
  become: yes
  become_user: "{{ user.name }}"

- name: Build and install YubiKey Personalization GUI
  command: "{{ aur.makepkg }} chdir=/home/{{ user.name }}/{{ aur.dir }}/yubikey-personalization-gui-git"
  tags:
    - aur
  become: yes
  become_user: "{{ user.name }}"
