---
- name: Install visidata
  aur:
    name: visidata
    user: "{{ user.name }}"
  tags:
    - aur

- name: Install additional libraries for visidata
  pacman:
    name:
      - python-xlrd
      - python-pandas
    state: present
