---
- name: Install mutt
  aur: name=neomutt user={{ user.name }}
  tags:
    - aur

- name: Jail mutt
  file: src=/usr/bin/firejail
        dest=/usr/local/bin/mutt
        state=link
  tags:
    - firejail

- name: Push mutt firejail profile
  copy: src=firejail/mutt.profile dest=/usr/local/etc/firejail/mutt.profile
  notify:
    - activate firejail profiles
  tags:
    - firejail

- name: Install urlview
  aur: name=urlview user={{ user.name }}
  tags:
    - aur

- name: Install notmuch
  pacman: name=notmuch state=present

- include: msmtp.yml
- include: isync.yml
- include: offlineimap.yml
- include: mailsync.yml
- include: contacts.yml
