---
- name: Install mutt
  aur: name=mutt-sidebar user={{ user.name }}
  tags:
    - aur

- name: Install urlview
  aur: name=urlview user={{ user.name }}
  tags:
    - aur

- name: Install notmuch
  pacman: name=notmuch state=present

- name: Push mail sync script
  copy: src=mailsync.sh dest=/usr/local/bin/mailsync mode=755

- include: msmtp.yml
- include: isync.yml
- include: offlineimap.yml
- include: contacts.yml
