---
- name: Install mutt
  aur: name=mutt-sidebar user={{ user.name }}
  tags:
    - aur

- name: Install urlview
  aur: name=urlview user={{ user.name }}
  tags:
    - aur

- name: Install OfflineIMAP
  pacman: name=offlineimap state=present

- name: Install msmtp
  pacman: name=msmtp-mta state=present

- name: Install notmuch
  pacman: name=notmuch state=present

- include: contacts.yml
