---
- name: Install texlive-core
  pacman:
    name: texlive-core
    state: present

- name: Install texlive-latexextra
  pacman:
    name: texlive-latexextra
    state: present

- name: Install texlive-most
  pacman:
    name: texlive-most
    state: present
